apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
  namespace: mediconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
        - name: doctor-service
          image: mediconnect/doctor-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/mediconnect_doctor
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  namespace: mediconnect
spec:
  selector:
    app: doctor-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP
